# Generated by Django 4.2 on 2026-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_variant_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Anonymous', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='No Subject', max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
